### ISSUE TITLE
Feature request: download wild viruses via Tor

### ISSUE THREAD

**Issue by srcr** [phage-nz/ph0neutria#1]
Perhaps downloading via Tor could be added

```
import socks
import socket
socks.set_default_proxy(socks.SOCKS5, "127.0.0.1", 9150)
socket.socket = socks.socksocket
```

**Comment by phage-nz** [comment]
It was my personal preference to use a VPN, but I'm happy to incorporate Tor proxy support into the next release (will be over the Xmas break).

Thanks for the suggestion.

**Comment by phage-nz** [comment]
Feature added in 0.6.0. Refer to readme for requirement information.
