### ISSUE TITLE
Viper API

### ISSUE THREAD

**Issue by frennkie** [phage-nz/ph0neutria#13]
I have been working on the Viper project for sometime now and - hopefully - soon they will merge my PR (viper-framework/viper#534). I noticed that this project makes use of the API and therefore I would like to 

* give you a heads up that there will be changes to the API (soon-ish)
* ask whether you could have a look into the new API design (before it's merged) and maybe give some feedback/improvement suggestions.. :-)

**Comment by frennkie** [comment]
I noticed that you are doing two requests for every file you upload to Viper. Therefore I added `note_title` and `note_body` to the file upload API. So with the new API you upload including a note in one step.

**Comment by phage-nz** [comment]
Thanks for letting me know of the impending changes @frennkie, and also for making the changes to how notes are created.

I'll do some testing against https://github.com/frennkie/viper/tree/django this coming week and see what feedback I can offer.

**Comment by phage-nz** [comment]
Testing completed. V3 support added: https://github.com/phage-nz/ph0neutria/commit/e61dfb8b09349af7e965ae9c1d576521ce9063cc

Great work on the Viper Web UI and API!
