### ISSUE TITLE
Viper Django issue

### ISSUE THREAD

**Issue by wkleinhenz** [phage-nz/ph0neutria#15]
This weekend I did a clean install of this project to use the new version of viper and ran into some issues. With the correct directories being owned by spider I ran into issues with ph0neutria submitting files. 

the script output is as follows:
adding to Viper: ace/MY_BIN/my_Bin.exe
Problem submitting file ace/MY_BIN/my_Bin.exe to Viper. Status code: 405. Continuing.

with viper showing that first POST was used to submit then followed by a GET request.:
2018-02-26 22:58:19 - django.server - WARNING - basehttp.py:124 - "GET /api/v3/project/default/malware/upload/ HTTP/1.1" 401 74
2018-02-26 22:58:21 - django.server - INFO - basehttp.py:124 - "POST /api/v3/project/default/malware/upload HTTP/1.1" 301 0

I can try to provide more info tomorrow, and once fixed i should be able to provide a rough ansible playbook for install

Thanks,
Will

**Comment by phage-nz** [comment]
Addressed in https://github.com/phage-nz/ph0neutria/commit/dbc3c55463e399fc1392965cb70513144ae3ad5d
