### ISSUE TITLE
Missing "/" in settings.conf

### ISSUE THREAD

**Issue by icepaule** [phage-nz/ph0neutria#16]
Hello Chris,

I had an error connecting to viper.

> Adding to Viper: frady.exe
> Problem connecting to Viper. Error: ('Connection aborted.', BadStatusLine("''",))

After adding a "/" at the end of the url in the settings conf, the issue went away.

So my correct entry looks like:
[Viper]
addurl=http://10.xx.xx.xx:8080/api/v3/project/default/malware/upload/

Maybe others have that issue too.  :-)

Cheers
Marcus

**Comment by wkleinhenz** [comment]
This fixed the issue i was facing in #15, thanks for the help @icepaule

**Comment by icepaule** [comment]
Glad I could help... ;-)

**Comment by phage-nz** [comment]
Thanks @icepaule - have addressed this in https://github.com/phage-nz/ph0neutria/commit/dbc3c55463e399fc1392965cb70513144ae3ad5d
