### ISSUE TITLE
ImportError: cannot import name soupParse

### ISSUE THREAD

**Issue by icepaule** [phage-nz/ph0neutria#2]
Hello Chris,

I was thrilled by your tool and thought it might be an excellent "feeder" of my Cuckoo and MISP instance.
Unfortunately, during the install, I have a little problem.

Could you help me with this?

root@ubuntu:/opt/ph0neutria# sudo -H -u spider python run.py
Traceback (most recent call last):
  File "run.py", line 5, in <module>
    from util.Malc0de import getMalc0deList
  File "/opt/ph0neutria/util/Malc0de.py", line 4, in <module>
    from StringUtils import isValidUrl, soupParse
ImportError: cannot import name soupParse
root@ubuntu:/opt/ph0neutria#

I've installed the beautifulsoup via easyinstall and it looks fine. Still it can't find the soupParse. (Nor can I) :-)

Thanks a lot for your help.

Cheers
Marcus

**Comment by phage-nz** [comment]
Hi,

This somehow looks to have dropped out in the last release.

Have added it back into stringUtils.

Thank you very much for this report.

Cheers,
Chris
