### ISSUE TITLE
No module named 'ConfigParser'

### ISSUE THREAD

**Issue by RecursiveNature** [phage-nz/ph0neutria#23]
I'm trying to test this program but there is an error when I run the run.py file. I did some research and it said that configparser was renamed to all lowercase. I'm not all to familiar with python, but what would be a fix for this issue?

**Comment by phage-nz** [comment]
Please ensure that you have the ConfigParser dependency installed, and that it successfully installs. Same applies to all other dependencies installed by the install script and by related software (Viper, etc).

ConfigParser was renamed to configparser in Python 3. It is still available in Python 2.7 as far as I'm aware. If you for some reason cannot get ConfigParser to import, configparser should be a suitable direct replacement. Just change the line 'from ConfigParser import SafeConfigParser' to 'from configparser import SafeConfigParser' where applicable.

**Comment by phage-nz** [comment]
No longer relevant with new release.

**Comment by msinghal95** [comment]
Hi, I was trying to run the "run.py" file, but i am getting this error

sudo -H -u spider python3 run.py
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from core.core_utils import start_core
  File "/opt/ph0neutria/core/core_utils.py", line 3, in <module>
    from .config_utils import get_base_config
  File "/opt/ph0neutria/core/config_utils.py", line 3, in <module>
    from ConfigParser import SafeConfigParser
ModuleNotFoundError: No module named 'ConfigParser'
Can you help me with this?
