### ISSUE TITLE
Send new malware to cuckoo

### ISSUE THREAD

**Issue by icepaule** [phage-nz/ph0neutria#3]
Hello Chris,

just to make you aware, I've added some code to have the cuckoo submit script on the same machine being triggered to analyse the new downloaded malware automatically.

Although I'm very sure that there is a much, much better way to add this functionality to your code, it might still be worth thinking of such an addition within the main distro.

I put this into FileUtil:

_## My additions
## submit to cuckoo
bashCommand = "/opt/cuckoo/utils/submit.py --remote [IP Address of your cuckoo]:[API-Port of your cuckoo] --memory --unique " + filePath
logging.info("Sending to Cuckoo: " + bashCommand)
os.system(bashCommand)
## My additions_

And please don't jam at me because of this obviouse bad style of code. I'm not in python at all, but it still works.  :-)

Cheers from the other side of the world.
Marcus

**Comment by phage-nz** [comment]
Hi,

Viper has the ability to send samples to Cuckoo, so I'd prefer not to double up on functionality if possible. However, now that I'm working on this project again I'll investigate how I may automate the submission to make your work easier.

Thanks.

**Comment by icepaule** [comment]
Hi,
wow, sounds great. I'll keep watching.  :-)

Cheers
Marcus
