### ISSUE TITLE
why the process of download does not start？the tmp dir is empty.

### ISSUE THREAD

**Issue by leixyou** [phage-nz/ph0neutria#35]
![image](https://user-images.githubusercontent.com/9550506/57692027-4fe3e800-7678-11e9-8816-93883f22c58e.png)

![image](https://user-images.githubusercontent.com/9550506/57692343-1d86ba80-7679-11e9-9a6c-e187608d8dd3.png)

**Comment by phage-nz** [comment]
I can't offer much help with such a small amount of information.

Files will not be downloaded for a variety of reasons, for example: if they no longer exist on the target, fail to download (connection timeout, etc), cannot be written to the tmp path (incorrect file permissions) etc.

Try to perform some more debugging. Read through the standard output and try to work out what is going on. Add some additional error handling in the code where you think it's failing, and catch the exceptions.

**Comment by leixyou** [comment]
![image](https://user-images.githubusercontent.com/9550506/57761842-ed025780-7730-11e9-812c-83083b886f49.png)

**Comment by phage-nz** [comment]
The errors pretty clearly states your problem. It cannot connect to the target. The target may have been taken offline, be stuck in an infinite redirect loop or be blocking Tor exit node addresses.

Some runs I get a very low success rate. Have to be patient and accept what you get.
