### ISSUE TITLE
Viper tags config Issue

### ISSUE THREAD

**Issue by wkleinhenz** [phage-nz/ph0neutria#5]
just downloaded and installed this, and on first run i get an error from the python script more specifically config parser.

it seems as though no value exists in the current config related to the newly added Viper addtags, although configpaser is still checking for it
here is the error just in case
![image](https://user-images.githubusercontent.com/18507996/30448278-5a9aa996-995c-11e7-9ca8-2a0c9ab18675.png)

**Comment by phage-nz** [comment]
'addtags' was missing in the config file as you suggested. Try adding addtags=yes as per:  

https://github.com/phage-nz/ph0neutria/commit/24dd428046d832d9c6a911800285ac0fa17b4cfc#diff-31f77aa247769bf649619ed3c53d0ba1

Or addtags=no if you wish to disable it.

**Comment by phage-nz** [comment]
Tested as not present in 0.9.0: https://github.com/phage-nz/ph0neutria/tree/v0.9.0
