### ISSUE TITLE
Don't store HTML files

### ISSUE THREAD

**Issue by Maxou56800** [phage-nz/ph0neutria#7]
Hello,

Did you allow me to add a piece of code for disable support of HTML pages?
Because sometime we get HTML page with: 
> "Site Suspended!"

I think its useless to store this content in Viper.

**Comment by phage-nz** [comment]
Hi. Over the coming weeks I'm going to be merging some functionality from my Malware Tracker (tracker.phage.nz) that will include this.

**Comment by phage-nz** [comment]
Agreed it is useless to store HTML and plaintext files. You'll find I now employ a whitelist in fileUtils.py as seen here: https://github.com/phage-nz/ph0neutria/blob/master/util/FileUtils.py#L168

If you have any feedback on this approach I'm more than happy to take it on board.

**Comment by phage-nz** [comment]
I'm going to close this issue. Please let me know if you have any feedback on the latest release.
